### ISSUE TITLE
[TODO] Fixed few things

### ISSUE THREAD

**Issue by lyrixx** [carew/carew#21]
This issue is a reminder for myself:

* [x] use new feature from symfony/console (verbosity, command tester, setTermDimension)
* [x] Better error management
* [x] Better output management 
* [x] Added phar support
