### ISSUE TITLE
[TODO] Fixed few things

### ISSUE THREAD

**Issue by lyrixx** [carew/carew#22]
This issue is a reminder for myself:
- [ ] use new feature from symfony/console (verbosity, command tester, setTermDimension
- [ ] Better error management
- [ ] Better output management
